services:
  - type: web
    name: neo4j-api-gateway
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: NEO4J_URI
        value: neo4j+s://a8062d04.databases.neo4j.io
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
